kind: Deployment
apiVersion: apps/v1
metadata:
   name: rajdevops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: rajdevops
   template:
      metadata:
        labels:
          app: rajdevops
      spec:
       containers:
        - name: rajdev
          image: rajeshjallu/pipeline-cicd
          imagePullPolicy: Always
          ports:
          - containerPort: 80
