kind: Service                             
apiVersion: v1
metadata:
  name: rajdevops
  labels:
    app: rajdevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: rajdevops                    
  type: LoadBalancer                   
